version: '3.8'

services:
  database:
    image: 'postgres:15-alpine'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASS}@database:5432/${DATABASE_NAME}
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/server.js"]

volumes:
  postgresql_data:
    driver: local
