version: '3'

services:
  # Database
  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASS}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
